server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.202:5432/cubetiq_spring_example
    username: cubetiq
    password: cubetiq007
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false